### PR TITLE
week 4 studio

### PR DESCRIPTION
**Pull request by knaaptime**
can you check the teams for me? (line 12 of studio.md)? I think the link needs to point to the updated teams

### CODE REVIEW

**Comment by knaaptime** [comment]
(note the notebook version runs perfectly on the course server, but I hit a failure trying to preview with quarto because there's some local file missing 

```
** [Errno 2] No such file or directory: 'merged.csv'**
```

**Comment by sjsrey** [comment]
That one was generated in a previous studio (studio 1).

I think if you render the entire course, that file should be generated for you?

**Comment by sjsrey** [comment]
[merged.csv](https://github.com/user-attachments/files/17018964/merged.csv)

**Comment by knaaptime** [comment]
got it. now missing cities

'/home/serge/data/385/studio02/cities.csv'

**Comment by knaaptime** [comment]
> I think if you render the entire course, that file should be generated for you? 

i thought so to, but it doesn't work if I `make render` (or `quarto render`)

**Comment by knaaptime** [comment]
(i see whats going on. Cities.csv exists on the server and this would run fine there. But I don't have quarto in my path on the course server. I think this is probably just a demo and you have the file structure mimiced locally?)

**Pull request merged**
